<?php 
$categorias = $this->categorias;
?>
			<link type="text/css" media="screen" rel="stylesheet"
				href="<?php echo $this->css_url; ?>sections/manager-categorias/index.css" />
			<div class="row-fluid">
			    <div class="span2">
			        <h3>Categorias</h3>
			    </div>
			
			    <div class="span2 offset8">
			    	<a href="<?php echo $this->url(array('action' => 'form'), 'ManagerCategoriasRouter', true);?>" class="btn btn-primary">
			    		<i class="icon-plus icon-white"></i>
			    		Adicionar
			    	</a>
			    </div>
			    
			    <table class="table table-bordered table-striped table-hover">
			        <thead>
				        <tr>
				            <th>Nome</th>
				            <th>Categoria Superior</th>
				            <th width="5%"></th>
				        </tr>
			        </thead>
			        <tbody>
<?php
if (!empty($categorias)) {
	foreach( $categorias as $categoria ) {
?>
				        <tr>
				            <td>
<?php echo $categoria['name'];?>
				            </td>
				            <td>
<?php echo $categoria['parent_name']; ?>
				            </td>
				            <td>
				           		<div class="btn-group">
									<button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
										<span class="caret"></span>
									</button>
									<ul class="dropdown-menu">
										<li><a href="<?php echo $this->url(array('action' => 'form', 'id' => $categoria['id']), 'ManagerCategoriasRouter', true);?>">Editar</a></li>
										<li><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $categoria['id']), 'ManagerCategoriasRouter', true); ?>">Excluir</a></li>
								  	</ul>
								</div>
				            </td>
				        </tr>
<?php
	}
}
else {
?>
				        <tr>
				            <td colspan="4">
				                <div align="center">
				                    Não há categorias cadastradas.
				                </div>
				            </td>
				        </tr>
<?php
}
?>
			        </tbody>
			    </table>
			</div>