<?php
$css_url = $this->css_url;
$js_url = $this->js_url;
$relative_path = $this->relative_path;
$absolute_path = $this->absolute_path;
$public_path = $this->public_path;
$absolute_url = $this->absolute_url;
$imgs_url = $this->imgs_url;
?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Shopping Limpeza :: Área Administrativa</title>
		
		<link rel="icon" href="<?php echo $imgs_url; ?>favicon.png"
			type="image/x-icon">
		<link rel="shortcut icon" href="<?php echo $imgs_url; ?>favicon.png"
			type="image/x-icon">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="author" content="Deyvison Rocha">
		<meta name="contact" content="deyvison@gmail.com">
		<meta name="robots" content="nofollow" />
		
		<link type="text/css" media="screen" rel="stylesheet"
			href="<?php echo $css_url . 'bootstrap.css'; ?>" />
		
		<!-- Le styles -->
		<style type="text/css">
			body {
				padding-top: 40px;
				padding-bottom: 40px;
				background-color: #f5f5f5;
			}
			
			.form-signin {
				max-width: 300px;
				padding: 19px 29px 29px;
				margin: 0 auto 20px;
				background-color: #fff;
				border: 1px solid #e5e5e5;
				-webkit-border-radius: 5px;
				-moz-border-radius: 5px;
				border-radius: 5px;
				-webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
				-moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
				box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
			}
			
			.form-signin .form-signin-heading,.form-signin .checkbox {
				margin-bottom: 10px;
			}
			
			.form-signin input[type="text"],.form-signin input[type="password"] {
				font-size: 16px;
				height: auto;
				margin-bottom: 15px;
				padding: 7px 9px;
			}
		</style>
		<link type="text/css" media="screen" rel="stylesheet"
			href="<?php echo $css_url . 'bootstrap-responsive.css'; ?>" />
	</head>

	<body>

		<div class="container">

			<form class="form-signin" method="post" action="<?php echo $this->url(array('controller' => 'manager', 'action' => 'login'), null, true); ?>">
				<?php echo $this->flashMessages(); ?>
		        <h2 class="form-signin-heading">Área Administrativa</h2>
		        <input type="text" class="input-block-level" placeholder="Usuário" name="user_login">
		        <input type="password" class="input-block-level" placeholder="Senha" name="password" >
		        <button class="btn btn-large btn-primary" type="submit">Entrar</button>
	      	</form>
	    </div> <!-- /container -->

	</body>
	<script type="text/javascript" src="<?php echo $js_url;?>jquery.js"></script>
	<script type="text/javascript" src="<?php echo $js_url;?>bootstrap.js"></script>
</html>
