<?php 
$produtos = $this->produtos;
?>
			<div class="row-fluid">
			    <div class="span2">
			        <h3>Produtos</h3>
			    </div>
			
			    <div class="span2 offset8">
			    	<a href="<?php echo $this->url(array('action' => 'form'), 'ManagerProdutosRouter', true);?>" class="btn btn-primary">
			    		<i class="icon-plus icon-white"></i>
			    		Adicionar
			    	</a>
			    </div>
			    
			    <table class="table table-bordered table-striped table-hover">
			        <thead>
				        <tr>
				            <th>Nome</th>
				            <th>Categoria</th>
				            <th>Descrição</th>
				            <th width="10%"></th>
				        </tr>
			        </thead>
			        <tbody>
<?php
if (!empty($produtos)) {
	foreach( $produtos as $produto ) {
?>
				        <tr>
				            <td>
<?php echo $produto['name'];?>
				            </td>
				            <td>
<?php echo $produto['category_name']; ?>
				            </td>
				            <td>
<?php echo $produto['description_short']; ?>
				            </td>
				            <td>
				            	<div class="btn-group">
									<button class="btn">Ação</button>
									<button class="btn dropdown-toggle" data-toggle="dropdown">
										<span class="caret"></span>
									</button>
									<ul class="dropdown-menu">
										<li><a href="<?php echo $this->url(array('action' => 'form', 'id' => $produto['id']), 'ManagerProdutosRouter', true);?>">Editar</a></li>
										<li><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $produto['id']), 'ManagerProdutosRouter', true); ?>">Excluir</a></li>
								  	</ul>
								</div>
				            </td>
				        </tr>
<?php
	}
}
else {
?>
				        <tr>
				            <td colspan="4">
				                <div align="center">
				                    Não há produtos cadastradas.
				                </div>
				            </td>
				        </tr>
<?php
}
?>
			        </tbody>
			    </table>
			</div>