<?php 
$categorias = $this->categorias;
$produtos = $this->produtos;
?>
			<section id="produtos" class="clearfix conteudo">

                <article class="grid_12">
                	<div class="grid_4 alpha box menu_produtos">
                		<h2 class="titulo"><span>Nossos</span> Produtos</h2>
                		
                		<div>
<?php
foreach ($categorias as $categoria):
	$categoria_id = $categoria['id'];
	$categoria_name = $categoria['name'];
	$category = Common::removeSpecialChars($categoria_name);
?>
							<h3><?php echo $categoria_name; ?></h3>

<?php
	if (!empty($produtos)):
?>
							<ul>
<?php 	
		foreach ($produtos as $produto):
			$produto_id = $produto['id'];
			$produto_name = $produto['name'];
			$produto_categoria_id = $produto['category_id'];
			$product = Common::removeSpecialChars($produto_name);
			
			if ($categoria_id == $produto_categoria_id):
?>
								<li><a href="<?php echo $this->url(array('category' => $category, 'product' => $product, 'id' => $produto_id), 'ProdutosRouter', true);?>"><?php echo $produto_name; ?></a></li>
<?php 
			endif;
		endforeach;
?>
							</ul>
<?php
	endif;
endforeach;
?>
						</div>
                	</div>

<?php 
$produto = $this->produto;
?>
                	<div class="grid_8 omega">
                		<ul class="clearfix box titulo breadcrumbs">
							<li><a href="<?php echo $this->relative_path; ?>" title="Voltar a Página Inicial">Home</a> > </li>
							<li><a href="#">Nossos Produtos</a> > </li>
							<li class="produto"><?php echo $produto['categoria']; ?></li>
						</ul>
						
						<h3 class="nome_prod"><?php echo $produto['name']; ?></h3>
						
						<table width="100%">
							<tbody>
								<tr class="azul">
									<td>Versões Disponíveis</td>
									<td>Aroma</td>
									<td>Cor</td>
									<td colspan="2">Informações Técnicas</td>
								</tr>
<?php 
$versoes = $produto['versoes'];

if (!empty($versoes)):
	foreach ($versoes as $versao):
?>
								<tr>
									<td><?php echo $versao['name']?></td>
									<td><?php echo $versao['fragrance']?></td>
									<td><?php echo $versao['color']?></td>
									<td><?php echo $versao['dilution']; ?></td>
									<td><?php echo $versao['packing']; ?></td>
								</tr>
<?php 
	endforeach;
endif;
?>
							</tbody>
						</table>
						
						<div class="grid_8 alpha omega caracteristicas">
							<div class="grid_5 alpha">
								<h3>Características</h3>
								<ul>
<?php 
$caracteristicas = $produto['caracteristicas'];
if (!empty($caracteristicas)):
	foreach ($caracteristicas as $caracteristica):
?>
									<li><?php echo $caracteristica['description']?></li>
<?php 
	endforeach;
endif;
?>
								</ul>
							</div>
							<div class="grid_3 omega">
<?php 
$imagem = $produto['image'];
if (!empty($imagem)):
?>
								<img src="<?php echo $this->imgs_url;?>produtos/<?php echo $imagem; ?>" alt="">
<?php 
endif;
?>
							</div>
						</div>
                	</div>
                	
                </article>

            </section>